version: '3.8'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGERES_USER: postgres
      POSTGRES_PASSWORD: ppap9090
      POSTGRES_DB: smart_tracker
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: